version: "2"

services: 

  mutech-iot-database-server:
    image: postgres
    restart: unless-stopped
    environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASS
        - POSTGRES_DB=$POSTGRES_DB_NAME
    ports:
        - "5432:5432"
    volumes:
        - database:/var/lib/postgresql/data

volumes:
  database:

